version: "3.9"

services:
  edge-app:
    build:
      context: ../..
      dockerfile: edge-app/deploy/docker/Dockerfile
    container_name: edge-app
    ports:
      - "8080:8080"
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - edge-data:/opt/edge-app
    restart: unless-stopped

volumes:
  edge-data:
